### ISSUE TITLE
Least square linear regression 

### ISSUE THREAD

**Issue by nilupulmanodya** [Hansajith98/Zero-to-hero-Machine-Learning#7]

**Comment by nilupulmanodya** [comment]
I would like to contribute a simple web app that takes the data points,it takes in
two arrays x and y. then find the line using least squares method. After plot these visually and print the coefficients, intercept.

**Comment by Hansajith98** [comment]
I'm sorry, Here you can add details about relevant topics, and there are no coding things. This repo like wiki about AI. Please consider making your contributions to the readme.md.
